#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

feign:
  hystrix:
    enabled: true # 开启Feign熔断


#security:
    #oauth2:
    #resource:
  #userInfoUri: http://localhost:8901/auth/user

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

swagger:
  enable: true


