spring:
  #    sleuth:
  #      sampler:
  #         percentage:  1
  zipkin:
    baseUrl:  http://localhost:9411
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
        binder:
          zkNodes: localhost
          brokers: localhost


#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://localhost:${server.port}/swagger-ui.html
    # 续约更新时间间隔（默认30秒）
    eureka.instance.lease-renewal-interval-in-seconds: 10
    # 续约到期时间（默认90秒）
    eureka.instance.lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

server:
  port: 8501

feign:
  hystrix:
    enabled: true # 开启Feign熔断


#security:
    #oauth2:
    #resource:
  #userInfoUri: http://localhost:8901/auth/user

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

swagger:
  enable: true


